image:
  repository: 835505308472.dkr.ecr.ap-south-1.amazonaws.com/hariprasad-app
  tag: "43"
  pullPolicy: Always

replicaCount: 2

service:
  type: NodePort        # changed from ClusterIP
  port: 80
  targetPort: 8080
  nodePort: 30080       # access via this port

ingress:
  enabled: false        # disable ingress — no domain needed

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

healthCheck:
  path: /actuator/health
  initialDelaySeconds: 15
  periodSeconds: 10
